require('user.plugins.plugins')
require('user.plugins.cmp')
require('user.plugins.colorscheme')
require('user.plugins.flutter-tools')
require("user.plugins.luasnip")
require("user.plugins.nvim-tree")
-- require('user.plugins.telescope')
require("user.plugins.fzf-lua")
require("user.plugins.treesitter")
require('user.plugins.lualine')
require('user.plugins.impatient')
require("user.plugins.project")
-- require("user.plugins.rooter")
require("user.plugins.nvim-notify")
require("user.plugins.toggle_term")
require("user.plugins.lazygit_toggle_term")
require("user.plugins.gitsigns")
require("user.plugins.stickybuf")
require("user.plugins.aerial")
require("user.plugins.mason")
-- require("user.plugins.java")
-- require("user.plugins.dashboard")
-- require("user.plugins.noice")
